apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-datacenter
  name: secret-datacenter
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: official
  containers:
  - image: ubuntu:latest
    name: secret-container-datacenter
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secret-volume
      mountPath: /opt/games

