version: '3.8'

services:
  web:
    container_name: php_apache
    image: php:apache
    ports:
      - "3000:80"
    volumes:
      - /var/www/html:/var/www/html
    depends_on:
      - db
  db:
    container_name: mysql_apache
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database_apache
      MARIADB_ROOT_PASSWORD: R00tP@ssw0rd
      MYSQL_USER: app_user
      MYSQL_PASSWORD: Str0ngP@ssw0rd