apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: print-envars-greeting
  name: print-envars-greeting
spec:
  containers:
  - env:
    - name: GREETING
      value: Welcome to
    - name: COMPANY
      value: xFusionCorp
    - name: GROUP
      value: Datacenter
    image: bash
    name: print-env-container
    command: ["/bin/sh", "-c", 'echo "$(GREETING) $(COMPANY) $(GROUP)"']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}