apiVersion: v1
kind: Pod
metadata:
  name: pod-datacenter
  labels:
    app: datacenter
spec:
  volumes:
    - name: datacenter-storage
      persistentVolumeClaim:
        claimName: pvc-datacenter
  containers:
    - name: container-datacenter
      image: nginx:latest
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: datacenter-storage


